quarkus.http.port=8083
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ecommerce
quarkus.datasource.password=ecommerce
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5436/notification_db
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=none
quarkus.log.console.format=%d{HH:mm:ss.SSS} %-5p [%c{2.}] [correlation=%X{correlationId}] %s%e%n
kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.order-events-notification.connector=smallrye-kafka
mp.messaging.incoming.order-events-notification.topic=order-events
mp.messaging.incoming.order-events-notification.group.id=notification-service
mp.messaging.incoming.order-events-notification.auto.offset.reset=earliest
mp.messaging.incoming.order-events-notification.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.outgoing.notification-dlq.connector=smallrye-kafka
mp.messaging.outgoing.notification-dlq.topic=notification-dlq
mp.messaging.outgoing.notification-dlq.value.serializer=org.apache.kafka.common.serialization.StringSerializer
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:notification;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.flyway.migrate-at-start=false
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.mp.messaging.incoming.order-events-notification.connector=smallrye-in-memory
%test.mp.messaging.outgoing.notification-dlq.connector=smallrye-in-memory
%test.quarkus.kafka.devservices.enabled=false
