CREATE TABLE notification(id UUID PRIMARY KEY,order_id UUID NOT NULL UNIQUE,email VARCHAR(320) NOT NULL,attempts INTEGER NOT NULL,sent_at TIMESTAMPTZ NOT NULL);
CREATE TABLE inbox_event(event_id UUID PRIMARY KEY,event_type VARCHAR(128) NOT NULL,received_at TIMESTAMPTZ NOT NULL,processed_at TIMESTAMPTZ);
