quarkus.http.port=8080
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ecommerce
quarkus.datasource.password=ecommerce
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/order_db
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false
quarkus.log.console.format=%d{HH:mm:ss.SSS} %-5p [%c{2.}] [correlation=%X{correlationId}] %s%e%n

kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.inventory-events-order.connector=smallrye-kafka
mp.messaging.incoming.inventory-events-order.topic=inventory-events
mp.messaging.incoming.inventory-events-order.group.id=order-service
mp.messaging.incoming.inventory-events-order.auto.offset.reset=earliest
mp.messaging.incoming.inventory-events-order.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.payment-events-order.connector=smallrye-kafka
mp.messaging.incoming.payment-events-order.topic=payment-events
mp.messaging.incoming.payment-events-order.group.id=order-service
mp.messaging.incoming.payment-events-order.auto.offset.reset=earliest
mp.messaging.incoming.payment-events-order.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:order;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.flyway.migrate-at-start=false
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.mp.messaging.incoming.inventory-events-order.connector=smallrye-in-memory
%test.mp.messaging.incoming.payment-events-order.connector=smallrye-in-memory
%test.quarkus.kafka.devservices.enabled=false
