quarkus.http.port=8081
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ecommerce
quarkus.datasource.password=ecommerce
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/inventory_db
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=none
quarkus.log.console.format=%d{HH:mm:ss.SSS} %-5p [%c{2.}] [correlation=%X{correlationId}] %s%e%n
kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.order-events-inventory.connector=smallrye-kafka
mp.messaging.incoming.order-events-inventory.topic=order-events
mp.messaging.incoming.order-events-inventory.group.id=inventory-service
mp.messaging.incoming.order-events-inventory.auto.offset.reset=earliest
mp.messaging.incoming.order-events-inventory.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.payment-events-inventory.connector=smallrye-kafka
mp.messaging.incoming.payment-events-inventory.topic=payment-events
mp.messaging.incoming.payment-events-inventory.group.id=inventory-service
mp.messaging.incoming.payment-events-inventory.auto.offset.reset=earliest
mp.messaging.incoming.payment-events-inventory.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:inventory;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.flyway.migrate-at-start=false
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.mp.messaging.incoming.order-events-inventory.connector=smallrye-in-memory
%test.mp.messaging.incoming.payment-events-inventory.connector=smallrye-in-memory
%test.quarkus.kafka.devservices.enabled=false
